name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: hanplus/candjava-code-server:4.3.0
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: hanplus/candjava-code-server:latest
